DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

/* SQLITE
CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
*/

/* MYSQL */
CREATE TABLE `pthompsoDB`.`user` (
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(2000) NOT NULL,
  password VARCHAR(2000) NOT NULL
) ;


CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(2000) NOT NULL,
  body VARCHAR(2000) NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);